apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iotdemo

bases:
- ../manuela-team-rolebindings

resources:
- iotdemo-namespace.yaml
- iotdemo-operatorgroup.yaml
- amq-operator-subscription.yaml

# Open data hub is optional
# - odh-operator-subscription.yaml
