apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-ml-workspace

bases:
- ../manuela-team-rolebindings

resources:
- manuela-ml-workspace-namespace.yaml
- manuela-ml-workspace-operatorgroup.yaml
- opendatahub-subscription.yaml


